# Generated by Django 5.1.2 on 2024-10-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='type',
            field=models.CharField(blank=True, choices=[('recuiter', 'Recuiter'), ('studemt', 'Student')], max_length=50, null=True),
        ),
    ]
