# Generated by Django 5.1.2 on 2024-10-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobed', '0002_usermodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='type',
            field=models.CharField(blank=True, choices=[('recuiter', 'Recuiter'), ('student', 'Student')], max_length=50, null=True),
        ),
    ]
