# Generated by Django 5.1.2 on 2024-10-16 18:36

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobed', '0003_alter_usermodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='type',
            field=models.CharField(blank=True, choices=[('Recuiter', 'Recuiter'), ('Student', 'Student')], max_length=50, null=True),
        ),
    ]
