# Generated by Django 5.1.2 on 2024-10-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobed', '0005_alter_usermodel_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
