# Generated by Django 5.1.2 on 2024-10-17 10:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobed', '0007_company_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
