# Generated by Django 5.1.2 on 2024-10-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobed', '0012_alter_usermodel_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(max_length=400, null=True),
        ),
    ]
