# Generated by Django 5.1.2 on 2024-10-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobed', '0014_alter_company_slug_alter_job_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_requirement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
