# Generated by Django 5.1.2 on 2024-10-23 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobed', '0016_job_job_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('description', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('start_month', models.DateField()),
                ('end_month', models.DateField()),
                ('link', models.URLField()),
                ('skills_used', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.DateField()),
                ('end_year', models.DateField()),
                ('degree', models.CharField(choices=[('Bachelor of Arts (B.A.)', 'Bachelor of Arts (B.A.)'), ('Bachelor of Science (B.Sc.)', 'Bachelor of Science (B.Sc.)'), ('Bachelor of Commerce (B.Com.)', 'Bachelor of Commerce (B.Com.)'), ('Bachelor of Technology (B.Tech.)', 'Bachelor of Technology (B.Tech.)'), ('Bachelor of Engineering (B.E.)', 'Bachelor of Engineering (B.E.)'), ('Bachelor of Medicine, Bachelor of Surgery (MBBS)', 'Bachelor of Medicine, Bachelor of Surgery (MBBS)'), ('Bachelor of Dental Surgery (BDS)', 'Bachelor of Dental Surgery (BDS)'), ('Bachelor of Business Administration (BBA)', 'Bachelor of Business Administration (BBA)'), ('Bachelor of Computer Applications (BCA)', 'Bachelor of Computer Applications (BCA)'), ('Bachelor of Pharmacy (B.Pharm)', 'Bachelor of Pharmacy (B.Pharm)'), ('Bachelor of Education (B.Ed.)', 'Bachelor of Education (B.Ed.)'), ('Bachelor of Law (LLB)', 'Bachelor of Law (LLB)'), ('Master of Arts (M.A.)', 'Master of Arts (M.A.)'), ('Master of Science (M.Sc.)', 'Master of Science (M.Sc.)'), ('Master of Commerce (M.Com.)', 'Master of Commerce (M.Com.)'), ('Master of Technology (M.Tech.)', 'Master of Technology (M.Tech.)'), ('Master of Engineering (M.E.)', 'Master of Engineering (M.E.)'), ('Master of Business Administration (MBA)', 'Master of Business Administration (MBA)'), ('Master of Computer Applications (MCA)', 'Master of Computer Applications (MCA)'), ('Doctor of Medicine (MD)', 'Doctor of Medicine (MD)'), ('Doctor of Philosophy (Ph.D.)', 'Doctor of Philosophy (Ph.D.)'), ('Diploma in Engineering', 'Diploma in Engineering'), ('Diploma in Pharmacy', 'Diploma in Pharmacy'), ('Post Graduate Diploma', 'Post Graduate Diploma')], max_length=200)),
                ('college_name', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('repo_link', models.URLField(blank=True, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('skills_used', models.CharField(choices=[('Communication', 'Communication'), ('Teamwork', 'Teamwork'), ('Leadership', 'Leadership'), ('Problem Solving', 'Problem Solving'), ('Time Management', 'Time Management'), ('Critical Thinking', 'Critical Thinking'), ('Adaptability', 'Adaptability'), ('Creativity', 'Creativity'), ('Emotional Intelligence', 'Emotional Intelligence'), ('Conflict Resolution', 'Conflict Resolution'), ('Decision Making', 'Decision Making'), ('Collaboration', 'Collaboration'), ('Negotiation', 'Negotiation'), ('Stress Management', 'Stress Management'), ('Attention to Detail', 'Attention to Detail'), ('Active Listening', 'Active Listening'), ('Public Speaking', 'Public Speaking'), ('Interpersonal Skills', 'Interpersonal Skills'), ('Organizational Skills', 'Organizational Skills'), ('Work Ethic', 'Work Ethic'), ('Self-Motivation', 'Self-Motivation'), ('Empathy', 'Empathy'), ('Flexibility', 'Flexibility'), ('Coaching & Mentoring', 'Coaching & Mentoring')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=200)),
                ('work_type', models.CharField(choices=[('Internship', 'Internship'), ('Part-Time', 'Part-Time'), ('Full-Time', 'Full-Time')])),
                ('company_website', models.CharField(max_length=200)),
                ('location', models.CharField(choices=[('Bengaluru', 'Bengaluru'), ('Hyderabad', 'Hyderabad'), ('Pune', 'Pune'), ('Chennai', 'Chennai'), ('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Gurugram', 'Gurugram'), ('Noida', 'Noida'), ('Kolkata', 'Kolkata'), ('Ahmedabad', 'Ahmedabad'), ('Coimbatore', 'Coimbatore'), ('Trivandrum', 'Trivandrum'), ('Kochi', 'Kochi'), ('Indore', 'Indore'), ('Jaipur', 'Jaipur'), ('Nagpur', 'Nagpur'), ('Mysuru', 'Mysuru'), ('Lucknow', 'Lucknow'), ('Surat', 'Surat'), ('Bhubaneswar', 'Bhubaneswar'), ('Visakhapatnam', 'Visakhapatnam'), ('Vadodara', 'Vadodara'), ('Patna', 'Patna'), ('Chandigarh', 'Chandigarh'), ('Bhopal', 'Bhopal'), ('Raipur', 'Raipur'), ('Vijayawada', 'Vijayawada'), ('Ranchi', 'Ranchi'), ('Jamshedpur', 'Jamshedpur'), ('Kanpur', 'Kanpur'), ('Agra', 'Agra'), ('Nashik', 'Nashik'), ('Gwalior', 'Gwalior'), ('Madurai', 'Madurai'), ('Rajkot', 'Rajkot'), ('Udaipur', 'Udaipur'), ('Aurangabad', 'Aurangabad'), ('Pondicherry', 'Pondicherry'), ('Gandhinagar', 'Gandhinagar'), ('Dehradun', 'Dehradun'), ('Shimla', 'Shimla'), ('Mangalore', 'Mangalore'), ('Tiruchirappalli', 'Tiruchirappalli'), ('Kozhikode', 'Kozhikode'), ('Vellore', 'Vellore'), ('Amritsar', 'Amritsar'), ('Faridabad', 'Faridabad'), ('Ghaziabad', 'Ghaziabad'), ('Meerut', 'Meerut'), ('Durgapur', 'Durgapur'), ('Siliguri', 'Siliguri'), ('Jodhpur', 'Jodhpur'), ('Aligarh', 'Aligarh'), ('Allahabad (Prayagraj)', 'Allahabad (Prayagraj)'), ('Varanasi', 'Varanasi'), ('Panaji', 'Panaji'), ('Guntur', 'Guntur'), ('Hubli', 'Hubli'), ('Belgaum', 'Belgaum'), ('Salem', 'Salem'), ('Thane', 'Thane'), ('Rourkela', 'Rourkela'), ('Jabalpur', 'Jabalpur'), ('Srinagar', 'Srinagar'), ('Ujjain', 'Ujjain'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Vapi', 'Vapi'), ('Anand', 'Anand'), ('Haldwani', 'Haldwani'), ('Moradabad', 'Moradabad'), ('Saharanpur', 'Saharanpur'), ('Jalgaon', 'Jalgaon'), ('Satara', 'Satara'), ('Tumkur', 'Tumkur'), ('Karimnagar', 'Karimnagar'), ('Bellary', 'Bellary'), ('Palakkad', 'Palakkad'), ('Erode', 'Erode'), ('Thanjavur', 'Thanjavur'), ('Tirunelveli', 'Tirunelveli')], max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('working', models.CharField(choices=[('Working Currently', 'Working Currently'), ('No', 'No')])),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='interests',
            field=models.CharField(blank=True, choices=[('Web Development', 'Web Development'), ('Data Science', 'Data Science'), ('Data Engineering', 'Data Engineering'), ('Frontend Development', 'Frontend Development'), ('Backend Development', 'Backend Development'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Cloud Computing', 'Cloud Computing'), ('DevOps', 'DevOps'), ('Machine Learning', 'Machine Learning'), ('Cybersecurity', 'Cybersecurity'), ('Mobile Development', 'Mobile Development'), ('UI/UX Design', 'UI/UX Design'), ('Game Development', 'Game Development'), ('Blockchain Development', 'Blockchain Development'), ('Internet of Things (IoT)', 'Internet of Things (IoT)')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='skills',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='achievements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobed.achievement'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='certifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobed.certification'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobed.education'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobed.projects'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='work_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobed.workexperince'),
        ),
    ]
