# Generated by Django 5.1.2 on 2024-11-01 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobed', '0018_remove_usermodel_work_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='user',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_education', to='jobed.education'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_work', to='jobed.workexperience'),
        ),
    ]
