# Generated by Django 5.1.2 on 2024-11-01 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobed', '0019_remove_achievement_user_remove_application_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='work',
            new_name='work_experience',
        ),
    ]
