# Generated by Django 5.1.2 on 2024-11-19 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobed', '0025_alter_education_end_year_alter_education_start_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='companyName',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='company_website',
            new_name='postition',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='working',
        ),
    ]
