# Generated by Django 5.1.2 on 2024-11-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobed', '0026_rename_companyname_workexperience_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='work_type',
            field=models.CharField(max_length=200),
        ),
    ]
